[package]
name = "middle-example-app"
version = "0.1.0"
edition = "2021"

[dependencies]
middle_wasm = { git = "https://github.com/Middle-dev/middle-wasm.git" }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 's'
lto = true